### ISSUE TITLE
getting errors while run the example?

### ISSUE THREAD

**Issue by dineshkumar4728** [scala/scala-seed.g8#24]
Hi,
       I am new to sbt.i am installing as per documentation everything is fine but when i run this example i am getting this errors.please suggest what i need to change or anything i missed?

java.lang.RuntimeException: Retrieval of org.scala-sbt.sbt-giter8-resolver:sbt-giter8-resolver:0.1.3 failed.
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbt.TemplateCommandUtil$.classpathForInfo(TemplateCommand.scala:136)
[error] 	at sbt.TemplateCommandUtil$.infoLoader(TemplateCommand.scala:98)
[error] 	at sbt.TemplateCommandUtil$.$anonfun$run$1(TemplateCommand.scala:65)
[error] 	at sbt.TemplateCommandUtil$.$anonfun$run$1$adapted(TemplateCommand.scala:64)
[error] 	at scala.collection.LinearSeqOptimized.find(LinearSeqOptimized.scala:111)
[error] 	at scala.collection.LinearSeqOptimized.find$(LinearSeqOptimized.scala:108)
[error] 	at scala.collection.immutable.List.find(List.scala:86)
[error] 	at sbt.TemplateCommandUtil$.run(TemplateCommand.scala:64)
[error] 	at sbt.TemplateCommandUtil$.runTemplate(TemplateCommand.scala:51)
[error] 	at sbt.TemplateCommandUtil$.$anonfun$templateCommand$2(TemplateCommand.scala:24)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:154)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:137)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:137)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:137)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:130)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:108)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:102)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:58)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:43)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Retrieval of org.scala-sbt.sbt-giter8-resolver:sbt-giter8-resolver:0.1.3 failed.
[error] Use 'last' for the full log.

Thanks

**Comment by jvr-ks** [comment]
You need not to install anything (if you have sbt already installed).
Just create a directory and a "project" subdirectory inside.
In the project subdirectory creat a file "build.properties" with one line containing the sbt version,
i.e.:
sbt.version=1.1.6
Now open a command prompt inside the new directory (not the subdirectory) and enter:
sbt new scala/scala-seed.g8

then
cd scala-seed-project
(if you did not change the name)

sbt run

-> hello

**Comment by SethTisue** [comment]
https://www.scala-lang.org/community/ has links on where to seek help using Scala and sbt
