### ISSUE TITLE
Would it make sense to add a .gitignore in the seed?

### ISSUE THREAD

**Issue by Dnomyar** [scala/scala-seed.g8#35]
Hey folks,

The title is self-descriptive.
I guess that the main problem would be to choose what to include is in the `gitignore`. 
IMHO, it would make sense to include OS and editor related gitignore. 

Could we imagine that the generation of the `.gitignore` is a parameter of the template?

Any thought?
Cheers

**Comment by Dnomyar** [comment]
@eed3si9n yes that is probably one ideal solution. But when you share your repositories with others, if only one does not have the global gitignore, everybody receives all unwanted files. If there is a versioned gitignore, this problem would not exist.
I guess it is also related to a workflow problem.

@SethTisue that sounds good 👍 
I am happy to do PR if it is fine

**Comment by SethTisue** [comment]
@Dnomyar yes please

**Comment by SethTisue** [comment]
fixed by #44
