### ISSUE TITLE
The already installed version of sbt is not reused

### ISSUE THREAD

**Issue by Joengenduvel** [scala/scala-seed.g8#5]
A fixed reference to sbt "0.13.13" is set in the properties file.
Can it be replaced by:
sbt sbtVersion | tail -n 1 | grep -oE '\d+\.\d+\.\d+'

This way you will not need to download 2 versions of sbt

**Comment by SethTisue** [comment]
In general, for build reproducibility, a project is expected to specify an exact sbt version, rather than just using whatever's lying around more globally. What you have globally is just a launcher, capable of launching many different versions of sbt.

see also #6

**Comment by dwijnand** [comment]
Nicely said. We should say that officially. /cc @eed3si9n

**Comment by SethTisue** [comment]
(closing, but @dwijnand, if there are release steps followed whenever a new sbt version comes out, perhaps you could add add "bump version in scala/scala-seed" to them, so updates like #13 don't get delayed?)

**Comment by dwijnand** [comment]
I'll add it to the checklist, thanks.

Btw, as of sbt 0.13.15 sbt writes out its version in project/build.properties: https://github.com/sbt/sbt/pull/3025 / https://github.com/sbt/sbt/releases/tag/v0.13.15.
