### ISSUE TITLE
Ability to define own organization and organizationName

### ISSUE THREAD

**Issue by luhtonen** [scala/scala-seed.g8#51]
It would be nice if it would be possible to define own `organization` and `organizationName` during project initialisation.

Usually project creation doesn't happen very often, but since this is a basic sbt template I'm using it to create projects for my experiments and I do it a lot. Now I have to rename those fields to my liking and to change package structure for every project I'm creating. Of cause there is several workarounds, but It would be nice if this template would give the ability to define those values during project initialisation and even better to be able to pass them as command line parameters.

**Comment by eed3si9n** [comment]
> I'm using it to create projects for my experiments and I do it a lot.

Do you publish those experiments as library?

**Comment by luhtonen** [comment]
> > I'm using it to create projects for my experiments and I do it a lot.
> 
> Do you publish those experiments as library?

No, I'm doing it more for my own education and some experiments for example with Akka.

**Comment by eed3si9n** [comment]
If you're not publishing the result, then I don't understand why organization matters.
Assuming many are using this template for the similar purpose of quick experiments, I don't think adding one more question is worth it.

**Comment by SethTisue** [comment]
agree
